# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "13.14"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    # fix git protocol https://github.com/orgs/community/discussions/26648#discussioncomment-3252721
    - run: git config --global url."git@github.com:".insteadOf git://github.com/
    - name: Install dependencies
      run: npm ci --ignore-scripts
    - run: npm run check-format
    - run: npm run build
    - name: Save build output
      uses: actions/upload-artifact@v4
      with:
        name: built-output
        path: ./dist
  
  deploy-site:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Load saved build output
        uses: actions/download-artifact@v4
        with:
          name: built-output
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.5.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          deploy_key: ${{ secrets.ACTION_DEPLOY_KEY }}
          publish_dir: ./dist
          commit_message: Deploy to GitHub Pages
